### ISSUE TITLE
Save API using incorrect log level

### ISSUE THREAD

**Issue by NotNite** [LazyDuchess/BRC-CommonAPI#1]
[SaveAPI.cs](https://github.com/LazyDuchess/BRC-CommonAPI/blob/b1fbe9cfc4e2bddd507b5080e7c6d8534635dc3b/SaveAPI.cs) and [SaveSlotHandlerPatch.cs](https://github.com/LazyDuchess/BRC-CommonAPI/blob/b1fbe9cfc4e2bddd507b5080e7c6d8534635dc3b/Patches/SaveSlotHandlerPatch.cs) both log to the console in Info every time the game is saved. This is quite often, so after a while your log can fill up with these meaningless lines. I suggest you remove them or set them to a better level (Debug, probably).

**Comment by LazyDuchess** [comment]
I've moved these to the debug level. Either way they only happen if the project is compiled with the COMMONAPI_DEBUG define.
